spring.application.name=appointment-saas
spring.datasource.url=jdbc:mysql://localhost:3306/appointment_saas
spring.datasource.username=root
spring.datasource.password=vaidik#PATEL38

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

jwt.secret=Y2FzQk9JbVh4R0nahwios0hNdE9qVnN4b2Zbajsei2lVQW5qRk1oWUdUYWJvQ1N3U1dJdAnq
jwt.expiration=86400000